import Head from "next/head";
import Navbar from "../components/Navbar";
import { useEffect, useState } from "react";
import Characters from "../components/Characters";
import Pagination from "../components/Pagination";

export default function Home() {
  const [characters, setCharacters] = useState([]);
  const [info, setInfo] = useState([]);
  const initialUrl = "https://rickandmortyapi.com/api/character";

  const fetchCharacters = (url) => {
    fetch(url)
      .then((response) => response.json())
      .then((data) => {
        setCharacters(data.results);
        setInfo(data.info);
      })

      .catch((error) => console.log(error));
  };

  const onPrevios = () => {
    fetchCharacters(info.prev)
  }

  const onNext = () => {
    fetchCharacters(info.next)
  }

  

  useEffect(() => {
    fetchCharacters(initialUrl);
  }, []);

  return (
    <div >
      <Head>
        <title>Rick And Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main >
        <Pagination prev={info.prev} next={info.next} onPrevious={onPrevios} onNext={onNext} className="pagination"/>
        <Characters characters={characters} />
        <Pagination prev={info.prev} next={info.next} onPrevious={onPrevios} onNext={onNext} className="pagination"/>
      </main>

      <footer ></footer>
    </div>
  );
}
